### ISSUE TITLE
JOSS Review: doi in paper

### ISSUE THREAD

**Issue by lheagy** [marcoalopez/GrainSizeTools#11]
Is there a doi that can be added to the Twiss and Moores reference in the JOSS paper? 

![image](https://user-images.githubusercontent.com/6361812/46159347-f20fa680-c234-11e8-9a9e-ad3d780d546d.png)

**Comment by marcoalopez** [comment]
There is no doi here but IBSNs. Specifically, this book has the following ISBN:
ISBN-10: 0716749513;
ISBN-13: 978-0-7167-4951-6

Indeed, the ISBN-10 was already provided in the paper.bib file. I don't know why it doesn't show up when building the pdf.

**Comment by lheagy** [comment]
:wave: Hi @arfon, should ISBN's show up in the references?

**Comment by arfon** [comment]
> 👋 Hi @arfon, should ISBN's show up in the references?

I think this is a know bug sorry: https://github.com/openjournals/joss/issues/392

**Comment by lheagy** [comment]
Thanks @arfon
