### ISSUE TITLE
JOSS review: jupyter notebooks

### ISSUE THREAD

**Issue by lheagy** [marcoalopez/GrainSizeTools#12]
Right now, the paths in the Jupyter notebooks are specific to your machine, it would be preferable to use relative paths so that when a user downloads them, they run out-of-the-box. e.g.

```
%run C:/Users/Marco/Documents/GitHub/GrainSizeTools/grain_size_tools/GrainSizeTools_script.py
```

could instead be 
```
%run ../grain_size_tools/GrainSizeTools_script.py
```

and similarly for the files included in the notebook. 
```
'../data_set.txt'
```

**Comment by marcoalopez** [comment]
You're right. Done it!
