### ISSUE TITLE
JOSS review: installation

### ISSUE THREAD

**Issue by lheagy** [marcoalopez/GrainSizeTools#7]
In the README and the docs, it is really helpful for useability to have a section on `installation`. Since the requirements are quite simple here, the installation instructions should be pretty straightforwad
- git clone the repository
- pip install requirements 
- test an example

(see for example: https://github.com/scikit-learn/scikit-learn#installation, https://github.com/seequent/properties#installation)

**Comment by marcoalopez** [comment]
I have modified the requirements section (now "requirements and development") to include how to clone or fork the project. I don't mention the installation via ``pip`` since the script is not available in PyPI (this will be done in the future as already commented elsewhere).
